sudo apt-get remove \
	baobab \
	ca-certificates-java \
	cheese \
	cheese-common \
	default-jre \
	default-jre-headless \
	gnome-calculator \
	gnome-calendar \
	gnome-disk-utility \
	gnome-screenshot \
	gnome-system-monitor \
	hexchat \
	hexchat-common \
	liblibreoffice-java \
	libreoffice-base \
	libreoffice-base-core \
	libreoffice-base-drivers \
	libreoffice-calc \
	libreoffice-common \
	libreoffice-core \
	libreoffice-draw \
	libreoffice-gnome \
	libreoffice-gtk3 \
	libreoffice-help-common \
	libreoffice-help-de \
	libreoffice-help-en-gb \
	libreoffice-help-en-us \
	libreoffice-help-es \
	libreoffice-help-fr \
	libreoffice-help-it \
	libreoffice-help-pt \
	libreoffice-help-ru \
	libreoffice-help-zh-cn \
	libreoffice-help-zh-tw \
	libreoffice-impress \
	libreoffice-java-common \
	libreoffice-l10n-de \
	libreoffice-l10n-en-gb \
	libreoffice-l10n-en-za \
	libreoffice-l10n-es \
	libreoffice-l10n-fr \
	libreoffice-l10n-it \
	libreoffice-l10n-pt \
	libreoffice-l10n-pt-br \
	libreoffice-l10n-ru \
	libreoffice-l10n-zh-cn \
	libreoffice-l10n-zh-tw \
	libreoffice-math \
	libreoffice-sdbc-hsqldb \
	libreoffice-style-colibre \
	libreoffice-writer \
	orca \
	python3-uno \
	rhythmbox \
	rhythmbox-data \
	rhythmbox-plugins \
	simple-scan \
	thunderbird \
	transmission-common \
	transmission-gtk \
	iagno \
  	lightsoff \
	four-in-a-row \
	gnome-robots \
	pegsolitaire \
	gnome-2048 \
	hitori \
	gnome-klotski \
	gnome-mines \
	gnome-mahjongg \
	gnome-sudoku \
	quadrapassel \
	swell-foop \
	gnome-tetravex \
	gnome-taquin \
	aisleriot \
	gnome-chess \
	five-or-more \
	gnome-nibbles \
	tali
